name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test01
      id: test01
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test01
        setup-command: pip install pytest
        command: pytest autograder.py::TestPart1Invert
        timeout: 10
        max-score: 10
    - name: test02
      id: test02
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test02
        setup-command: pip install pytest
        command: pytest autograder.py::TestPart2DisplayChannel
        timeout: 10
        max-score: 10
    - name: test03
      id: test03
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test03
        setup-command: pip install pytest
        command: pytest autograder.py::TestPart3Flip
        timeout: 10
        max-score: 20
    - name: test04
      id: test04
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test04
        setup-command: pip install pytest
        command: pytest autograder.py::TestPart4Grayscale
        timeout: 10
        max-score: 20
    - name: test05
      id: test05
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test05
        setup-command: pip install pytest
        command: pytest autograder.py::TestPart5Brightness
        timeout: 10
        max-score: 20
    - name: test06
      id: test06
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test06
        setup-command: pip install pytest
        command: pytest autograder.py::TestPart6Contrast
        timeout: 10
        max-score: 20
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST01_RESULTS: "${{steps.test01.outputs.result}}"
        TEST02_RESULTS: "${{steps.test02.outputs.result}}"
        TEST03_RESULTS: "${{steps.test03.outputs.result}}"
        TEST04_RESULTS: "${{steps.test04.outputs.result}}"
        TEST05_RESULTS: "${{steps.test05.outputs.result}}"
        TEST06_RESULTS: "${{steps.test06.outputs.result}}"
      with:
        runners: test01,test02,test03,test04,test05,test06
